version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo Running linter
      - npm run lint || echo "No lint script found"

  build:
    commands:
      - echo Running tests
      - npm test || echo "No tests yet"

  post_build:
    commands:
      - echo Running smoke checks
      # file is at repo root, not in public
      - test -f index.html || { echo "index.html not found"; exit 1; }
      # check content that really exists
      - grep -q "Omotoyosi" index.html   || { echo "Expected text Omotoyosi not found"; exit 1; }
      - grep -q "DevOps" index.html      || { echo "Expected text DevOps not found"; exit 1; }
      - echo All checks passed

artifacts:
  files:
    - server.js
    - index.html
    - package.json
    - package-lock.json